# Site settings
title: My Personal Website
description: Welcome to my personal website!
theme: minimal-mistakes

# Other settings
# Add any additional configuration settings specific to your website or the theme
